export const tags = [
  // Cartoon

  //   "Classic cartoons",
  //   "Modern cartoons",
  //   "Cartoon TV shows",
  //   "Kids cartoons",
  //   "Cartoon movies",
  //   "Superhero cartoons",
  //   "Comedy cartoons",
  //   "Japanese cartoons",
  //   "Anime",
  //   "American cartoons",
  //   "3D cartoons",
  //   "2D cartoons",
  //   "Adventure cartoons",
  //   "Sci-fi cartoons",
  //   "Fantasy cartoons",
  //   "Short cartoons",
  //   "Funny cartoons",

  // Animals
  "Mammals",
  "Birds",
  "Reptiles",
  "Amphibians",
  "Insects",
  "Wild animals",
  "Pets",
  "Dogs",
  "Cats",
  "Lions",
  "Tigers",
  "Elephants",
  "Pandas",
  "Owls",
  "Horses",
  "Fish",
  "Dolphins",
  "Sharks",
  "Turtles",
  "Penguins",
  "Rabbits",
  "Bears",
  "Deer",
  "Wolves",
  "Crocodiles",
  "Kangaroos",
  "Koalas",
  "Butterflies",
  "Bees",
  "Tortoises",

  // Characters
  //   "Heroes",
  //   "Villains",
  //   "Sidekicks",
  //   "Funny characters",
  //   "Animal cartoon characters",
  //   "Human characters",
  "Robots",
  "Aliens",
  //   "Wizard characters",
  "Knights",
  "Pirates",
  "Ninjas",
  "Samurai",
  //   "Fantasy characters",
  //   "Monster characters",
  //   "Vampires",
  //   "Werewolves",
  //   "Fairies",
  //   "Mythological characters",
  //   "Fairy tale characters",

  // Mixed (Cartoons, Animals, and Characters)
  //   "Anthropomorphic animals",
  //   "Funny animal cartoons",
  //   "Animal cartoon series",
  //   "Famous cartoon characters",
  //   "Animated animal world",
  //   "Dinosaur characters",
  //   "Dragon characters",
  //   "Animal adventure cartoons",
  //   "Explorer characters",
  //   "Mythical animals",
  //   "Musical cartoons",
  //   "Sports cartoons",
  //   "Animal mascots",
  //   "Animal heroes",
  //   "Favorite cartoon characters",
  //   "Forest animals",
  //   "Family cartoons",
  //   "Sea creatures",
  //   "Imaginative cartoon worlds",
  //   "Classic nostalgic cartoons",

  // Cartoon Characters
  "Mickey Mouse",
  "Donald Duck",
  "Bugs Bunny",
  "Tom and Jerry",
  "Scooby-Doo",
  "SpongeBob SquarePants",
  "Patrick Star",
  "Bart Simpson",
  "Homer Simpson",
  "Stewie Griffin",
  "Peter Griffin",
  "Daffy Duck",
  "Goofy",
  "Pluto",
  "Shrek",
  "Woody",
  "Buzz Lightyear",
  "Elsa",
  "Anna",
  "Olaf",
  "Simba",
  "Pumbaa",
  "Timon",
  "Stitch",
  "Po Kung Fu Panda",
  "Pikachu",
  "Ash Ketchum",
  "Naruto Uzumaki",
  "Goku",
  "Vegeta",
  "Sailor Moon",
  "Totoro",
  "Chihiro Spirited Away",
  "Doraemon",
  "Nobita",
  "Charlie Brown",
  "Snoopy",
  "Garfield",
  "Felix the Cat",
  "Popeye",
  "The Powerpuff Girls",
  "Johnny Bravo",
  "Dexter",
  "Courage the Cowardly Dog",
  "Ben 10",
];
